images:
- name: event-bridge-manager
  newName: quay.io/5733d9e2be6485d52ffa08870cabdee0/fleet-manager
  newTag: manager:2be3cee486d5e764bdb616a62abe77ed1277ac79
- name: event-bridge-shard-operator
  newName: quay.io/5733d9e2be6485d52ffa08870cabdee0/fleet-shard
  newTag: ocp-shard:ocp-jvm
patchesStrategicMerge:
- manager/patches/deploy.yaml
- manager/patches/deploy-config.yaml
- manager/patches/postgres-config.yaml
- shard/patches/deploy-config.yaml
resources:
- ../base
- manager
- shard
- observability
