images:
- name: event-bridge-manager
  newName: quay.io/5733d9e2be6485d52ffa08870cabdee0/fleet-manager
  newTag: 6415829690cfc9eac70ac761a4b354aa40e8e954-jvm
- name: event-bridge-shard-operator
  newName: quay.io/5733d9e2be6485d52ffa08870cabdee0/fleet-shard
  newTag: ocp-6415829690cfc9eac70ac761a4b354aa40e8e954-jvm
patchesStrategicMerge:
- manager/patches/deploy.yaml
- manager/patches/deploy-config.yaml
- manager/patches/postgres-config.yaml
- shard/patches/deploy-config.yaml
resources:
- ../base
- manager
- shard
- observability
